#!/bin/bash

# Set the terminal variable (change this to your preferred terminal)
TERMINAL="kitty"  # Change this to your preferred terminal, e.g., "xterm", "konsole", "terminator", etc.

# Get the destination directory using dmenufm
DESTINATION=$(echo $(dmenufm -p -t))

# Check if DESTINATION is not empty
if [ -n "$DESTINATION" ]; then
    OPTS=("qu" "dl" "x")

    while true; do
        SELOPT=$(printf '%s\n' "${OPTS[@]}" | dmenu -fn "Liberation Mono" -nb black -nf white -sb white -sf black -p "$(echo $DESTINATION | awk -F/ '{print $NF}')")
        
        case "$SELOPT" in
            qu)
                QUERY=$(echo "" | dmenu -fn "Liberation Mono" -nb black -nf white -sb white -sf black -p '::query')
                $TERMINAL -e soulseek q "$QUERY"
                ;;
            dl)
                FLAGS=("codec")
                FLAGSELECT=$(printf '%s\n' "${FLAGS[@]}" | dmenu -fn "Liberation Mono" -nb black -nf white -sb white -sf black -p 'Select option for download')
                
                case "$FLAGSELECT" in
                    codec)
                        CODEC=$(echo -e "MP3\nFLAC" | dmenu -fn "Liberation Mono" -nb black -nf white -sb white -sf black -p 'Select codec')
			CODEC=$(echo $CODEC | tr '[:upper:]' '[:lower:]')
			if [ $CODEC = "mp3" ]; then
                        	QUALITY=$(echo -e "128\n192\n256\n320" | dmenu -fn "Liberation Mono" -nb black -nf white -sb white -sf black -p 'Select quality') 
			fi
                esac
                
		QUERY=$(echo "" | dmenu -fn "Liberation Mono" -nb black -nf white -sb white -sf black -p 'Enter download query:')

                # Ensure QUERY is set before executing the command
                if [ -n "$QUERY" ]; then
                    $TERMINAL -e soulseek d "$QUERY" -d "$DESTINATION" -m "$CODEC" -q "$QUALITY"
                fi
                ;;
	   x)
             break
	     ;;
        esac
    done
fi
